i3: /home/alex/.config/i3/config
polybar: /home/alex/.config/polybar/config.ini
xresources: /home/alex/.Xresources
nitrogen: /home/alex/.config/nitrogen/bg-saved.cfg
wallpaper-path: /home/alex/.config/nitrogen/
bash: /home/alex/.bashrc
